In [49]:
import numpy as np
import random as rd

In [50]:
numero_amostra = 5

In [51]:
x = np.zeros(numero_amostra)

In [52]:
x

array([0., 0., 0., 0., 0.])

In [53]:
for i in range(0, numero_amostra):
  x[i] = rd.randrange(0, 100)

In [54]:
x

array([51., 23., 53., 92., 94.])

In [55]:
probabilidade = np.zeros(numero_amostra)

In [56]:
soma = sum(x)

In [57]:
soma

313.0

In [58]:
for i in range(numero_amostra):
  probabilidade[i] = x[i]/soma

In [59]:
probabilidade

array([0.1629393 , 0.07348243, 0.16932907, 0.29392971, 0.30031949])

In [60]:
print(sum(probabilidade))

1.0


In [61]:
esperanca = 0
i = 0
while i < numero_amostra:
  esperanca += x[i]*probabilidade[i]
  i += 1

In [62]:
esperanca

74.24600638977635

In [63]:
variancia = 0
i = 0
while i < numero_amostra:
  variancia += ((x[i]-esperanca)**2)*probabilidade[i]
  i += 1

In [64]:
variancia

567.2973083322275